# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_setup.ipynb.

# %% auto 0
__all__ = ['running_in_colab', 'setup_colab', 'setup']

# %% ../00_setup.ipynb 2
from IPython.display import set_matplotlib_formats

# %% ../00_setup.ipynb 3
def running_in_colab():
    try:
        if 'google.colab' in str(get_ipython()):
          return True
    except Exception:
        pass
    return False


def setup_colab():
    "Sets up Colab"
    assert running_in_colab(), "You do not appear to be running in Colab"


def setup():
    "Sets up ds_tut. First run `%pip install -Uqq ds_tut` in a cell"
    if running_in_colab():
        setup_colab()
    set_matplotlib_formats("retina")
